version: '3.8'

services:

  postgres-clients:
    image: postgres:17
    container_name: postgres-db-clients
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tarpuqPass
      POSTGRES_DB: bank-clients
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data-clients
    networks:
      - app-network

  postgres-transactions:
    image: postgres:15
    container_name: postgres-db-transactions
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: bank-transactions
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data-transactions
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-server
    ports:
      - "5672:5672" # Puerto conexión de RabbitMQ
      - "15672:15672" # Puerto GUI de RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  # Microservicio bank-clients
  ms-clients:
    image: ms-clients
    container_name: ms-clients
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-clients:5432/bank-clients
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pass123
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    networks:
      - app-network
    depends_on:
      - postgres-clients
      - rabbitmq

  # Microservicio bank-transactions
  bank-transactions:
    image: bank-transactions
    container_name: bank-transactions
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-transactions:5432/bank-transactions
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pass123
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    networks:
      - app-network
    depends_on:
      - postgres-transactions
      - rabbitmq

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local